---
title: "RandomForest"
author: "Hanying Ji"
date: "2018/3/19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Cross Validation Function for Random Forest
```{r}  
if(!require("randomForest")){
    install.packages("randomForest")
}
if(!require("caret")){
    install.packages("caret")
}
if(!require("e1071")){
    install.packages("e1071")
}
if(!require("ggplot2")){ 
    install.packages("ggplot2")
}
library(randomForest)
library(caret)
library(e1071)
library(knitr)
library(ggplot2)

customRF <- list(type = "Classification", library = "randomForest", loop = NULL)
customRF$parameters <- data.frame(parameter = c("mtry", "ntree"), class = rep("numeric", 2), label = c("mtry", "ntree"))
customRF$grid <- function(x, y, len = NULL, search = "grid") {}
customRF$fit <- function(x, y, wts, param, lev, last, weights, classProbs, ...){
  randomForest(x, y, mtry = param$mtry, ntree=param$ntree, ...)
}
customRF$predict <- function(modelFit, newdata, preProc = NULL, submodels = NULL){
  predict(modelFit, newdata)
}
customRF$prob <- function(modelFit, newdata, preProc = NULL, submodels = NULL){
  predict(modelFit, newdata, type = "prob")
}

customRF$sort <- function(x) x[order(x[,1]),]
customRF$levels <- function(x) x$classes


RF<-function(feature_file,way="readcsv",header_TF=FALSE){
  setwd("/Users/JHY/Documents/2018SpringCourse/Applied Data Science/Spring2018-Project3-Group1")
  test_index<-read.table("./data/train/TEST-NUMBER.txt")
  test_index<-as.vector(t(test_index))
  if(way=="readcsv"){
    feature<-read.csv(feature_file,header = header_TF)
  }
  if(way=="load"){
    load(feature_file)
    feature<-dat
    colnames(feature)<-as.character(c(1:ncol(feature)))
  }
  if(feature_file==".output/features/SIFT_train.csv"){
    feature<-feature[,2:ncol(feature)]
  }
  label<-read.csv("./data/train/label_train.csv")
  train_data<-feature[-test_index,]
  train_label<-label[-test_index,]$label
  
  control <- trainControl(method="cv", number=5)
  tunegrid <- expand.grid(mtry=c(round(sqrt(ncol(train_data))-3):round(sqrt(ncol(train_data))+3)), ntree=c(500,1000,1500,2000))
  set.seed(24)
  custom<-caret::train(train_data,as.factor(train_label),method=customRF,metric="Accuracy",tuneGrid=tunegrid,trControl=control)
  summary(custom)
  plot(custom)
}
```

#HOG
```{r}
RF("./output/features/HOG.RData",way="load")
```


#LBP
```{r}
RF(".output/features/lbp/lbp.csv")
```


#SIFT
```{r}
#RF("SIFT_train.csv")
```

#GIST
```{r}
#RF("./gist/gist10.csv",header=TRUE)
```
